services:
  app:
    image: ghcr.io/janthoxo/caps-ex1:sha-47063cd
    ports:
      - "3030:3030"
    depends_on:
      - mongodb
    environment:
      - DATABASE_URI=${DATABASE_URI}
      - DB_NAME=${DB_NAME}
    restart: unless-stopped

  mongodb:
    image: mongo:7.0
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_DATABASE=${DB_NAME}
    volumes:
      - mongodb-data:/data/db
    restart: unless-stopped

volumes:
  mongodb-data: