services:
  server:
    image: ghcr.io/janthoxo/caps-ex1/server:main
    ports:
      - "8080:8080"
    depends_on:
      - mongodb
    environment:
      - DATABASE_URI=mongodb://mongodb:27017
      - DB_NAME=${DB_NAME:-caps-ex3}
      - SERVER_PORT=8080
    restart: unless-stopped

  mongodb:
    image: mongo:7.0
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_DATABASE=${DB_NAME:-caps-ex3}
    volumes:
      - mongodb-data:/data/db
    restart: unless-stopped

  client:
    image: ghcr.io/janthoxo/caps-ex1/client:main
    ports:
      - "3030:3030"
    environment:
      - API_URI=http://server:8080
      - SERVER_PORT=3030
    restart: unless-stopped

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - server
      - client
    restart: unless-stopped

volumes:
  mongodb-data: