name: build
on: 
  pull_request:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24'
          check-latest: true

      - name: Download dependencies
        run: go mod download

      - name: Build
        run: go build -v -o bookstore-app ./cmd/

      # - name: Run tests
      #   run: go test -v ./...
