name: deploy docker images

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: AZURE
      url: "https://${{ vars.PUBLIC_IP }}.nip.io"
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Copy Docker Compose File From Repo to VM Host
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ vars.PUBLIC_IP }}
          username: ${{ vars.AZURE_USER }}
          key: ${{ secrets.AZURE_PRIVATE_KEY }}
          source: "./docker-compose.prod.yml,./nginx.conf"
          target: /home/${{ vars.AZURE_USER }}

      - name: SSH to VM and Create .env
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ vars.PUBLIC_IP }}
          username: ${{ vars.AZURE_USER }}
          key: ${{ secrets.AZURE_PRIVATE_KEY }}
          script: |
            mv docker-compose.prod.yml docker-compose.yml
            rm .env
            touch .env
            echo "DOMAIN=${{ vars.PUBLIC_IP }}.nip.io" >> .env
            echo "SHARE_DB_USER=${{ secrets.DB_NAME }}" >> .env

      - name: SSH to VM and Execute Docker-Compose Up
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ vars.PUBLIC_IP }}
          username: ${{ vars.AZURE_USER }}
          key: ${{ secrets.AZURE_PRIVATE_KEY }}
          script: |
            echo "Logging into Docker registry..."
            echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin
            echo "Starting Docker Compose..."
            docker compose -f docker-compose.yml --env-file=.env up --pull=always -d